name: Build

on:
  pull_request:
  push:
    branches: ['**']

jobs:
  nextflow:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: MillironX/setup-nextflow@v1
      # On validates flow:
      #   Confirms workflow is valid
      #   Confirms all containers are available
      - name: Validate workflow
        run: |
          nextflow -c nextflow.stubRun.config run main.nf \
            -profile test -stub-run \
            --core_ref data/cgpwgs_ref/GRCh37/archives/core_ref_GRCh37d5.tar.gz \
            --snv_indel data/cgpwgs_ref/GRCh37/archives/SNV_INDEL_ref_GRCh37d5-fragment.tar.gz \
            --cnv_sv data/cgpwgs_ref/GRCh37/archives/CNV_SV_ref_GRCh37d5_brass6+.tar.gz \
            --annot data/cgpwgs_ref/GRCh37/archives/VAGrENT_ref_GRCh37d5_ensembl_75.tar.gz \
            --qc_genotype data/cgpwgs_ref/GRCh37/archives/qcGenotype_GRCh37d5.tar.gz \
            --pairs data/test.csv
